spring:
  datasource:
    url: jdbc:mysql://localhost:3307/growlog_travel?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&connectTimeout=10000&socketTimeout=10000&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: growlog
    password: WBVYsDtCraFhLkSVNY9v

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  data:
    redis:
      host: localhost
      port: 6379

mail:
  from: ${MAIL_FROM}

server:
  port: 8080

logging:
  level:
    com.zaxxer.hikari: DEBUG
    com.mysql.cj.jdbc: DEBUG
toss:
  secret-key: ${TOSS_SECRET_KEY}